import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  TextInput,
  Modal,
  StyleSheet,
} from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withTiming,
  withRepeat,
  withSequence,
} from 'react-native-reanimated';
import { BlurView } from 'expo-blur';
import { getQuestionsForProfession } from '../../../../lib/aiQuestions';
import { COLORS } from '../constants';
import { styles } from '../styles';

interface AiAssessmentModalProps {
  visible: boolean;
  onClose: () => void;
  profession: string;
  onComplete: (
    tier: string,
    score: number,
    feedback: string,
    autogeneratedBio: string,
    recommendedSkills: string[]
  ) => void;
}

export const AiAssessmentModal = ({
  visible,
  onClose,
  profession,
  onComplete,
}: AiAssessmentModalProps) => {
  const [assessmentStep, setAssessmentStep] = useState(0); // 0: Welcome, 1-3: Questions, 4: Analyzing, 5: Results
  const [aiAnswers, setAiAnswers] = useState({ ans1: '', ans2: '', ans3: 3 });
  const [analyzingText, setAnalyzingText] = useState('');
  const [assessmentResult, setAssessmentResult] = useState<{
    score: number;
    tier: string;
    feedback: string;
    autogeneratedBio: string;
    recommendedSkills: string[];
  } | null>(null);

  // Reanimated shared values
  const orbScale = useSharedValue(1);
  const orbOpacity = useSharedValue(0.6);

  const getAiRecommendedSkills = (profession: string, ans1: string, ans2: string): string[] => {
    const skills: string[] = [];
    const fullText = (ans1 + ' ' + ans2).toLowerCase();

    if (fullText.includes('equipo') || fullText.includes('colabora')) {
      skills.push('Trabajo en Equipo');
    }
    if (fullText.includes('comunic') || fullText.includes('explic')) {
      skills.push('Comunicación Asertiva');
    }
    if (fullText.includes('resolv') || fullText.includes('soluc') || fullText.includes('problem')) {
      skills.push('Resolución de Problemas');
    }

    const lowerProf = profession.toLowerCase();
    if (
      lowerProf.includes('program') ||
      lowerProf.includes('desarroll') ||
      lowerProf.includes('tech') ||
      lowerProf.includes('ingeni')
    ) {
      skills.push('Arquitectura Limpia');
      if (skills.length < 2) skills.push('Análisis de Sistemas');
    } else if (
      lowerProf.includes('abogado') ||
      lowerProf.includes('derecho') ||
      lowerProf.includes('legal')
    ) {
      skills.push('Análisis Regulatorio');
      if (skills.length < 2) skills.push('Pensamiento Analítico');
    } else if (
      lowerProf.includes('cocina') ||
      lowerProf.includes('chef') ||
      lowerProf.includes('gastrono')
    ) {
      skills.push('Eficiencia Operativa');
      if (skills.length < 2) skills.push('Control de Calidad');
    } else if (
      lowerProf.includes('medic') ||
      lowerProf.includes('salud') ||
      lowerProf.includes('enfermer')
    ) {
      skills.push('Toma de Decisiones Crítica');
      if (skills.length < 2) skills.push('Empatía Clínica');
    } else {
      skills.push('Orientación a Resultados');
      if (skills.length < 2) skills.push('Gestión del Tiempo');
    }

    return skills.slice(0, 2);
  };

  const runGrading = () => {
    const len1 = aiAnswers.ans1.trim().split(/\s+/).filter(Boolean).length;
    const len2 = aiAnswers.ans2.trim().split(/\s+/).filter(Boolean).length;
    const scaleVal = aiAnswers.ans3; // 1-5

    // Average length of answers
    const avgLen = (len1 + len2) / 2;

    // Define high-impact professional keywords for rigor assessment
    let specializedKeywords: string[] = [];
    const qList = getQuestionsForProfession(profession);
    const firstQ = qList[0]?.id || '';

    if (firstQ.startsWith('tech_')) {
      specializedKeywords = [
        'lazy',
        'profile',
        'memoria',
        'clean',
        'mvvm',
        'microservicios',
        'api',
        'graphql',
        'aws',
        'gcp',
        'cicd',
        'pipeline',
        'git',
        'patrón',
        'hilo',
        'bloqueo',
        'virtual',
        'código',
        'desarrollo',
        'nube',
      ];
    } else if (firstQ.startsWith('chef_')) {
      specializedKeywords = [
        'mermas',
        'inventario',
        'costo',
        'receta',
        'haccp',
        'higiene',
        'almacenamiento',
        'temperatura',
        'platillo',
        'brigada',
        'insumo',
        'cocina',
        'salón',
        'desperdicio',
        'calidad',
      ];
    } else if (firstQ.startsWith('legal_')) {
      specializedKeywords = [
        'contrato',
        'riesgo',
        'indemnidad',
        'penalidad',
        'disputa',
        'jurisprudencia',
        'doctrina',
        'recurso',
        'litigio',
        'mercantil',
        'ley',
        'norma',
        'cláusula',
        'tribunal',
        'legal',
      ];
    } else if (firstQ.startsWith('health_')) {
      specializedKeywords = [
        'paciente',
        'clínico',
        'diagnóstico',
        'sintomatología',
        'vital',
        'empatía',
        'acls',
        'bls',
        'urgencia',
        'médico',
        'protocolo',
        'síntoma',
        'clínica',
        'ética',
        'soporte',
      ];
    } else if (firstQ.startsWith('admin_')) {
      specializedKeywords = [
        'caja',
        'cash',
        'liquidez',
        'cobranza',
        'contable',
        'erp',
        'sap',
        'oracle',
        'excel',
        'presupuesto',
        'conciliación',
        'facturación',
        'costo',
        'administración',
        'proceso',
      ];
    } else if (firstQ.startsWith('sales_')) {
      specializedKeywords = [
        'campaña',
        'roi',
        'cac',
        'ltv',
        'conversión',
        'crm',
        'salesforce',
        'hubspot',
        'cliente',
        'embudo',
        'ticket',
        'objeción',
        'cierre',
        'venta',
        'marketing',
        'b2b',
        'b2c',
      ];
    } else if (firstQ.startsWith('edu_')) {
      specializedKeywords = [
        'pedagógica',
        'inclusión',
        'aula',
        'instruccional',
        'lms',
        'moodle',
        'canvas',
        'currículo',
        'competencias',
        'docencia',
        'enseñanza',
        'estudiante',
        'evaluación',
        'aprendizaje',
      ];
    } else if (firstQ.startsWith('trade_')) {
      specializedKeywords = [
        'seguridad',
        'epp',
        'riesgo',
        'diagnóstico',
        'planos',
        'cuadrilla',
        'material',
        'obra',
        'protocolo',
        'falla',
        'avería',
        'herramienta',
        'maestro',
        'oficio',
        'plano',
      ];
    } else {
      specializedKeywords = [
        'reto',
        'liderazgo',
        'resolución',
        'priorizar',
        'presión',
        'plazo',
        'comunicación',
        'conflicto',
        'equipo',
        'metodología',
        'planificación',
        'gestión',
        'solución',
        'trabajo',
      ];
    }

    // Base score is strictly structured (start at 35)
    let score = 35;

    // 1. Answer length scoring (Rigor de respuesta)
    if (avgLen > 50) score += 25;
    else if (avgLen > 30) score += 18;
    else if (avgLen > 15) score += 10;
    else if (avgLen > 5) score += 4;

    // 2. Self-evaluation confidence points (up to +20)
    score += (scaleVal - 1) * 5;

    // 3. Keyword depth matching
    const fullText = (aiAnswers.ans1 + ' ' + aiAnswers.ans2).toLowerCase();
    let keywordHits = 0;
    specializedKeywords.forEach((word) => {
      if (fullText.includes(word)) keywordHits++;
    });
    score += Math.min(keywordHits * 1.5, 15);

    // 4. Mismatch / Overclaim Penalty
    let incongruenceNote = '';
    if (scaleVal >= 4 && avgLen < 15) {
      score -= 20;
      incongruenceNote =
        'Se detectó incongruencia heurística entre la autoevaluación muy alta y la brevedad de los argumentos técnicos proporcionados.';
    } else if (scaleVal === 5 && avgLen < 25) {
      score -= 10;
      incongruenceNote =
        'Se observó una leve discrepancia entre la máxima confianza declarada y la extensión descriptiva de las respuestas prácticas.';
    }

    // 5. Strict caps based on descriptive depth
    if (avgLen < 15) {
      score = Math.min(score, 65); // Cap to Junior Acreditado
    } else if (avgLen < 28) {
      score = Math.min(score, 79); // Cap to Mid-Level Acreditado
    }

    // Round and cap score limits
    score = Math.max(10, Math.min(Math.round(score), 98));

    // Stricter Tiers mapping (Senior requires at least 88% and extensive answers)
    let tier = 'Junior Acreditado';
    if (score >= 88 && avgLen >= 28) {
      tier = 'Senior Acreditado';
    } else if (score >= 72) {
      tier = 'Mid-Level Acreditado';
    }

    // Tailor strengths feedback
    let feedback = '';
    if (firstQ.startsWith('tech_')) {
      feedback =
        score >= 80
          ? 'Demuestra un excelente dominio de patrones de diseño avanzados, optimización de hilo principal y una sólida comprensión de infraestructura en la nube y pipelines de CI/CD.'
          : 'Posee conocimientos sólidos de desarrollo de software, estructurando bien las soluciones básicas. Se beneficiará de profundizar en patrones avanzados y optimización de memoria.';
    } else if (firstQ.startsWith('chef_')) {
      feedback =
        score >= 80
          ? 'Destaca por su alto rigor conceptual en control de mermas e inventarios y su gran capacidad de liderazgo asertivo y organización bajo situaciones de alta presión en cocina.'
          : 'Muestra buen criterio operativo y manejo básico de recetas y costos. Se aconseja fortalecer el liderazgo de brigadas y planeación avanzada en situaciones imprevistas.';
    } else if (firstQ.startsWith('legal_')) {
      feedback =
        score >= 80
          ? 'Posee una gran capacidad de análisis de riesgos contractuales y estructuración jurídica persuasiva ante lagunas en jurisprudencia o normativas complejas.'
          : 'Evidencia un correcto dominio de la doctrina jurídica general y contratos estándar. Se recomienda profundizar en argumentación de recursos complejos y litigación avanzada.';
    } else if (firstQ.startsWith('health_')) {
      feedback =
        score >= 80
          ? 'Refleja una sólida formación en soporte vital avanzado y una excepcional empatía y claridad asertiva al comunicar situaciones clínicas complejas a familiares.'
          : 'Muestra buen manejo de protocolos médicos generales y primeros auxilios. Se aconseja continuar su desarrollo en toma de decisiones críticas bajo escenarios inestables.';
    } else if (firstQ.startsWith('admin_')) {
      feedback =
        score >= 80
          ? 'Excelente modelado financiero y diseño de flujo de caja proyectado, además de una clara visión metodológica para optimizar procesos administrativos ineficientes.'
          : 'Domina tareas administrativas y contables recurrentes. Se sugiere avanzar en el uso de ERPs de gran escala y formulación de presupuestos a largo plazo.';
    } else if (firstQ.startsWith('sales_')) {
      feedback =
        score >= 80
          ? 'Gran manejo de embudos de conversión, alta competencia en el uso de herramientas CRM y una excelente metodología estructurada para captación de clientes de alto valor.'
          : 'Muestra facilidad para el cierre de ventas básico y trato al público. Le favorecerá capacitarse en analítica de datos, embudos automatizados e integraciones avanzadas de CRM.';
    } else if (firstQ.startsWith('edu_')) {
      feedback =
        score >= 80
          ? 'Sobresaliente diseño instruccional, excelente manejo de metodologías inclusivas y adaptabilidad pedagógica activa frente a aulas diversas.'
          : 'Evidencia buenas habilidades de docencia y empatía en el aula. Se recomienda fortalecer el dominio de entornos virtuales de aprendizaje (LMS) y diseño curricular.';
    } else if (firstQ.startsWith('trade_')) {
      feedback =
        score >= 80
          ? 'Alto compromiso con normativas de seguridad ocupacional y protocolos preventivos, con un enfoque lógico y estructurado para diagnóstico y resolución de fallas técnicas críticas.'
          : 'Muestra buen manejo técnico operativo y destreza en tareas físicas del oficio. Se beneficiará de capacitarse en supervisión de personal e interpretación compleja de planos.';
    } else {
      feedback =
        score >= 80
          ? 'Demuestra una excelente terminología profesional, sólida metodología en gestión de plazos competitivos bajo presión y gran resolución de conflictos interpersonales.'
          : 'Presenta un perfil balanceado con potencial de crecimiento. Se recomienda enfocar esfuerzos en el desarrollo de liderazgo colaborativo y habilidades blandas bajo estrés.';
    }

    const recommendedSkills = getAiRecommendedSkills(profession, aiAnswers.ans1, aiAnswers.ans2);

    // DYNAMIC & PERSONALIZED "SOBRE MÍ" PROFILE GENERATOR
    let aboutMeIntro = '';
    let aboutMeDepth = '';
    let aboutMeConfidence = '';
    let aboutMeSpecialty = '';

    // 1. Introduction based on certified level & title
    if (tier === 'Senior Acreditado') {
      aboutMeIntro = `Profesional con amplia trayectoria y acreditación de nivel Senior como ${profession} en Aptly (puntuación técnica del ${score}%). Se destaca por su robustez estratégica, rigurosidad metodológica y una sólida competencia para liderar la resolución de problemas complejos.`;
    } else if (tier === 'Mid-Level Acreditado') {
      aboutMeIntro = `Especialista con perfil balanceado acreditado en rango Mid-Level como ${profession} en Aptly (puntuación técnica del ${score}%). Cuenta con destrezas prácticas consolidadas en desafíos operativos y de planificación del sector.`;
    } else {
      aboutMeIntro = `Profesional ágil y de rápida ejecución acreditado con rango Junior como ${profession} en Aptly (puntuación técnica del ${score}%). Posee un gran potencial de crecimiento, adaptabilidad técnica y enfoque práctico inmediato.`;
    }

    // 2. Answer depth personalization
    if (avgLen >= 40) {
      aboutMeDepth =
        'Durante la evaluación de Aptly, demostró una elocuencia técnica excepcional, sustentando sus metodologías con alto rigor conceptual y planeación avanzada.';
    } else if (avgLen >= 20) {
      aboutMeDepth =
        'Evidenció un enfoque pragmático orientado a objetivos directos, estructurando de forma muy coherente y solvente sus respuestas técnicas.';
    } else {
      aboutMeDepth =
        'Su perfil prioriza la resolución ágil y concreta, orientándose al soporte de la continuidad operativa mediante ejecuciones precisas.';
    }

    // 3. Confidence level personalization
    if (scaleVal >= 4) {
      aboutMeConfidence =
        'Muestra una sólida seguridad técnica en sus destrezas, iniciativa proactiva y capacidad natural para asumir responsabilidades de alta demanda bajo presión.';
    } else {
      aboutMeConfidence =
        'Destaca por su perfil altamente colaborativo, enfocado en el trabajo armónico en equipo, el aprendizaje continuo y una comunicación asertiva sólida.';
    }

    // 4. Keyword specialized matches
    if (keywordHits >= 6) {
      aboutMeSpecialty = `Domina con soltura vocabulario y herramientas avanzadas de la industria como ${specializedKeywords.slice(0, 3).join(', ')}, integrándose perfectamente con metodologías modernas.`;
    } else if (keywordHits >= 2) {
      aboutMeSpecialty = `Posee conocimientos prácticos relacionados con ${specializedKeywords.slice(0, 2).join(', ')}, guiando su desempeño bajo estándares de calidad organizacionales.`;
    } else {
      aboutMeSpecialty =
        'Enfoca sus esfuerzos técnicos en el cumplimiento riguroso de normativas básicas y en la contribución eficiente a los flujos organizacionales.';
    }

    // Combined Personalized Biography
    const autogeneratedBio = `${aboutMeIntro} ${aboutMeDepth} ${aboutMeConfidence} ${aboutMeSpecialty}${incongruenceNote ? `\n\n*Nota del evaluador:* ${incongruenceNote}` : ''}`;

    setAssessmentResult({ score, tier, feedback, autogeneratedBio, recommendedSkills });
    setAssessmentStep(5);
  };

  useEffect(() => {
    if (assessmentStep === 4) {
      orbScale.value = withRepeat(
        withSequence(withTiming(1.3, { duration: 1000 }), withTiming(1.0, { duration: 1000 })),
        -1,
        true
      );
      orbOpacity.value = withRepeat(
        withSequence(withTiming(1.0, { duration: 1000 }), withTiming(0.4, { duration: 1000 })),
        -1,
        true
      );

      setAnalyzingText('Aptly AI iniciando análisis heurístico...');

      const t1 = setTimeout(() => {
        setAnalyzingText('Evaluando vocabulario técnico e interpretando escenarios...');
      }, 1500);

      const t2 = setTimeout(() => {
        setAnalyzingText('Comparando habilidades con estándares de la industria...');
      }, 3000);

      const t3 = setTimeout(() => {
        setAnalyzingText('Generando reporte de competencias y certificado...');
      }, 4500);

      const t4 = setTimeout(() => {
        runGrading();
      }, 6000);

      return () => {
        clearTimeout(t1);
        clearTimeout(t2);
        clearTimeout(t3);
        clearTimeout(t4);
        orbScale.value = 1;
        orbOpacity.value = 0.6;
      };
    }
  }, [assessmentStep]);

  // Reset modal state when visible becomes true
  useEffect(() => {
    if (visible) {
      setAssessmentStep(0);
      setAiAnswers({ ans1: '', ans2: '', ans3: 3 });
      setAssessmentResult(null);
    }
  }, [visible]);

  const animatedOrbStyle = useAnimatedStyle(() => {
    return {
      transform: [{ scale: orbScale.value }],
      opacity: orbOpacity.value,
    };
  });

  return (
    <Modal visible={visible} animationType="fade" transparent={true} onRequestClose={onClose}>
      <View style={styles.aiModalContainer}>
        <BlurView style={StyleSheet.absoluteFillObject} intensity={40} tint="dark" />
        <KeyboardAvoidingView
          behavior={Platform.OS === 'ios' ? 'padding' : undefined}
          style={{ flex: 1, width: '100%', justifyContent: 'center', alignItems: 'center' }}>
          <View style={styles.aiModalContent}>
            {/* Header */}
            {assessmentStep < 4 && (
              <View style={styles.aiModalHeader}>
                <Text style={styles.aiModalHeaderTitle}>Evaluador de IA</Text>
                <TouchableOpacity onPress={onClose} style={styles.aiModalCloseBtn}>
                  <MaterialCommunityIcons name="close" size={24} color="#FFF" />
                </TouchableOpacity>
              </View>
            )}

            {/* Step 0: Welcome Screen */}
            {assessmentStep === 0 && (
              <ScrollView contentContainerStyle={styles.aiStepScroll}>
                <View style={{ alignItems: 'center', marginVertical: 15 }}>
                  <View style={styles.aiBrainIconBg}>
                    <MaterialCommunityIcons name="brain" size={48} color={COLORS.candidate} />
                  </View>
                </View>
                <Text style={styles.aiStepTitle}>Certificación de Competencias con IA</Text>
                <Text style={styles.aiStepSubtitle}>
                  El sistema de evaluación inteligente de Aptly validará tu nivel para la profesión
                  seleccionada:
                </Text>
                <View style={styles.professionPill}>
                  <MaterialCommunityIcons
                    name="briefcase"
                    size={20}
                    color={COLORS.candidate}
                    style={{ marginRight: 8 }}
                  />
                  <Text style={styles.professionPillText}>{profession || 'Sin profesión'}</Text>
                </View>

                <View style={styles.aiFeatureList}>
                  <View style={styles.aiFeatureItem}>
                    <MaterialCommunityIcons
                      name="checkbox-marked-circle-outline"
                      size={20}
                      color={COLORS.candidate}
                    />
                    <Text style={styles.aiFeatureText}>
                      3 Preguntas técnicas y situaciones de crisis.
                    </Text>
                  </View>
                  <View style={styles.aiFeatureItem}>
                    <MaterialCommunityIcons
                      name="badge-account-outline"
                      size={20}
                      color={COLORS.candidate}
                    />
                    <Text style={styles.aiFeatureText}>
                      Certificado con puntuación neón en tu perfil.
                    </Text>
                  </View>
                  <View style={styles.aiFeatureItem}>
                    <MaterialCommunityIcons name="eye" size={20} color={COLORS.candidate} />
                    <Text style={styles.aiFeatureText}>
                      Altamente valorado y visible para las empresas.
                    </Text>
                  </View>
                </View>

                <TouchableOpacity
                  style={styles.aiActionBtn}
                  onPress={() => {
                    setAssessmentStep(1);
                    setAiAnswers({ ans1: '', ans2: '', ans3: 3 });
                  }}>
                  <Text style={styles.aiActionBtnText}>✨ Iniciar Evaluación con IA</Text>
                </TouchableOpacity>

                <TouchableOpacity onPress={onClose} style={{ alignSelf: 'center', marginTop: 15 }}>
                  <Text style={{ color: '#64748b', fontWeight: '600' }}>Tal vez más tarde</Text>
                </TouchableOpacity>
              </ScrollView>
            )}

            {/* Step 1 & 2: Open Questions */}
            {(assessmentStep === 1 || assessmentStep === 2) &&
              (() => {
                const questions = getQuestionsForProfession(profession);
                const currentQ = questions[assessmentStep - 1];
                const currentVal = assessmentStep === 1 ? aiAnswers.ans1 : aiAnswers.ans2;
                const setVal = (text: string) => {
                  setAiAnswers((prev) => ({
                    ...prev,
                    [assessmentStep === 1 ? 'ans1' : 'ans2']: text,
                  }));
                };

                return (
                  <ScrollView
                    contentContainerStyle={styles.aiStepScroll}
                    keyboardShouldPersistTaps="handled">
                    {/* Progress Meter */}
                    <View style={styles.aiProgressRow}>
                      <Text style={styles.aiProgressText}>Pregunta {assessmentStep} de 3</Text>
                      <View style={styles.aiProgressBarBg}>
                        <View
                          style={[
                            styles.aiProgressBarFill,
                            { width: `${(assessmentStep / 3) * 100}%` },
                          ]}
                        />
                      </View>
                    </View>

                    <Text style={styles.aiQuestionText}>{currentQ?.question}</Text>

                    <View style={styles.aiInputContainer}>
                      <TextInput
                        multiline
                        numberOfLines={6}
                        placeholder={
                          currentQ?.placeholder || 'Escribe tu respuesta técnica detallada aquí...'
                        }
                        placeholderTextColor="#475569"
                        value={currentVal}
                        onChangeText={setVal}
                        style={styles.aiTextInput}
                        maxLength={500}
                      />
                      <Text style={styles.charCounter}>{currentVal.length}/500</Text>
                    </View>

                    <TouchableOpacity
                      style={[
                        styles.aiActionBtn,
                        { opacity: currentVal.trim().length > 10 ? 1 : 0.6 },
                      ]}
                      disabled={currentVal.trim().length <= 10}
                      onPress={() => {
                        if (assessmentStep === 1) {
                          setAssessmentStep(2);
                        } else {
                          setAssessmentStep(3);
                        }
                      }}>
                      <Text style={styles.aiActionBtnText}>Continuar</Text>
                    </TouchableOpacity>

                    <Text style={styles.aiWarningHint}>
                      Escribe al menos 10 caracteres para continuar.
                    </Text>
                  </ScrollView>
                );
              })()}

            {/* Step 3: Scale Question */}
            {assessmentStep === 3 &&
              (() => {
                const questions = getQuestionsForProfession(profession);
                const currentQ = questions[2];
                const scaleVal = aiAnswers.ans3;

                return (
                  <ScrollView contentContainerStyle={styles.aiStepScroll}>
                    {/* Progress Meter */}
                    <View style={styles.aiProgressRow}>
                      <Text style={styles.aiProgressText}>Pregunta 3 de 3</Text>
                      <View style={styles.aiProgressBarBg}>
                        <View style={[styles.aiProgressBarFill, { width: '100%' }]} />
                      </View>
                    </View>

                    <Text style={styles.aiQuestionText}>{currentQ?.question}</Text>

                    {/* 1-5 Scale Custom Pressables */}
                    <View style={styles.scaleContainer}>
                      {[1, 2, 3, 4, 5].map((num) => {
                        const isSelected = scaleVal === num;
                        return (
                          <TouchableOpacity
                            key={num}
                            activeOpacity={0.8}
                            onPress={() => setAiAnswers((prev) => ({ ...prev, ans3: num }))}
                            style={[styles.scaleItem, isSelected && styles.scaleItemActive]}>
                            <Text
                              style={[styles.scaleNumber, isSelected && styles.scaleNumberActive]}>
                              {num}
                            </Text>
                          </TouchableOpacity>
                        );
                      })}
                    </View>

                    <View style={styles.scaleLabelsRow}>
                      <Text style={styles.scaleLabelText}>
                        {currentQ?.scaleLabels?.min || 'Básico'}
                      </Text>
                      <Text style={styles.scaleLabelText}>
                        {currentQ?.scaleLabels?.max || 'Experto'}
                      </Text>
                    </View>

                    <TouchableOpacity
                      style={styles.aiActionBtn}
                      onPress={() => {
                        setAssessmentStep(4); // Trigger analyzing
                      }}>
                      <Text style={styles.aiActionBtnText}>✨ Finalizar y Evaluar</Text>
                    </TouchableOpacity>
                  </ScrollView>
                );
              })()}

            {/* Step 4: Analyzing State */}
            {assessmentStep === 4 && (
              <View style={styles.aiAnalyzingContainer}>
                <Animated.View style={[styles.aiAnalyzingOrb, animatedOrbStyle]}>
                  <MaterialCommunityIcons name="brain" size={50} color="#FFF" />
                </Animated.View>

                <Text style={styles.aiAnalyzingTitle}>Procesando con Inteligencia Artificial</Text>
                <Text style={styles.aiAnalyzingText}>{analyzingText}</Text>
              </View>
            )}

            {/* Step 5: Results / Certificate */}
            {assessmentStep === 5 && assessmentResult && (
              <ScrollView contentContainerStyle={styles.aiStepScroll}>
                <Text style={[styles.aiStepTitle, { fontSize: 24, marginBottom: 5 }]}>
                  ¡Evaluación Completada!
                </Text>
                <Text style={styles.aiStepSubtitle}>
                  Este es tu nivel y reporte acreditado de competencias:
                </Text>

                {/* Certificate Card */}
                <View style={styles.certificateCard}>
                  <View style={styles.certificateHeader}>
                    <MaterialCommunityIcons name="seal" size={24} color={COLORS.candidate} />
                    <Text style={styles.certificateHeaderText}>APTLY CERTIFIED PROFILE</Text>
                  </View>

                  <View style={styles.certBody}>
                    <View style={styles.certScoreContainer}>
                      <Text style={styles.certScore}>{assessmentResult.score}%</Text>
                      <Text style={styles.certScoreSub}>SCORE GLOBAL</Text>
                    </View>

                    <View style={styles.certMeta}>
                      <Text style={styles.certTierLabel}>NIVEL ASIGNADO</Text>
                      <Text style={styles.certTier}>{assessmentResult.tier}</Text>

                      <Text style={styles.certProfession}>{profession}</Text>
                    </View>
                  </View>

                  <View style={styles.certDivider} />

                  <View style={styles.certFeedbackContainer}>
                    <Text style={styles.certFeedbackTitle}>REPORTE DE FORTALEZAS (IA)</Text>
                    <Text style={styles.certFeedbackText}>{assessmentResult.feedback}</Text>
                  </View>
                </View>

                <TouchableOpacity
                  style={styles.aiActionBtn}
                  onPress={() => {
                    onComplete(
                      assessmentResult.tier,
                      assessmentResult.score,
                      assessmentResult.feedback,
                      assessmentResult.autogeneratedBio,
                      assessmentResult.recommendedSkills
                    );
                  }}>
                  <Text style={styles.aiActionBtnText}>Aplicar Nivel y Continuar</Text>
                </TouchableOpacity>

                <TouchableOpacity
                  onPress={() => {
                    setAssessmentStep(0);
                    setAiAnswers({ ans1: '', ans2: '', ans3: 3 });
                  }}
                  style={{ alignSelf: 'center', marginTop: 15 }}>
                  <Text style={{ color: COLORS.candidate, fontWeight: '600' }}>
                    Repetir Evaluación
                  </Text>
                </TouchableOpacity>
              </ScrollView>
            )}
          </View>
        </KeyboardAvoidingView>
      </View>
    </Modal>
  );
};
