import { StyleSheet } from 'react-native';
import { COLORS } from './constants';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  safeArea: { flex: 1 },
  progressBarContainer: {
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.05)',
    width: '100%',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 2,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 100,
  },
  stepContainer: {
    flex: 1,
  },
  questionTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 10,
    lineHeight: 36,
  },
  questionSubtitle: {
    fontSize: 15,
    color: COLORS.textSecondary,
    marginBottom: 24,
  },
  sectorsContainer: { marginTop: 20 },
  sectorsLabel: { color: COLORS.textSecondary, fontSize: 13, marginBottom: 12, fontWeight: '600' },
  sectorsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  sectorTag: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  sectorTagActive: {
    borderColor: COLORS.company,
    backgroundColor: 'rgba(255,0,92,0.1)',
    shadowColor: COLORS.company,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  sectorTagCandidateActive: {
    borderColor: COLORS.candidate,
    backgroundColor: 'rgba(0,163,255,0.1)',
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  sectorTagText: { color: COLORS.textSecondary, fontSize: 14, fontWeight: '500' },
  sectorTagTextActive: { color: '#FFF', fontWeight: '800' },

  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    backgroundColor: COLORS.background,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
  },
  backBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextBtnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '800',
  },
  avatarPicker: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(0,163,255,0.05)',
    borderWidth: 1,
    borderColor: COLORS.candidate,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholder: { alignItems: 'center', justifyContent: 'center' },
  avatarImage: { width: '100%', height: '100%' },
  dateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginBottom: 16,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    backgroundColor: '#1A1A1C',
  },
  dateText: { flex: 1, color: '#FFF', fontSize: 16, marginLeft: 12 },
  datePlaceholder: { color: '#64748b' },
  iosDatePickerContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: COLORS.card,
    zIndex: 999,
    paddingBottom: 30,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 10,
  },
  iosDatePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  socialBtn: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialText: { color: 'white', fontWeight: 'bold', marginLeft: 8 },
  divider: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  dividerLine: { flex: 1, height: 1, backgroundColor: 'rgba(255,255,255,0.1)' },
  dividerText: { color: COLORS.textSecondary, paddingHorizontal: 10, fontSize: 12 },
  areaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.02)',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  areaCardActive: {
    borderColor: COLORS.company,
    backgroundColor: 'rgba(255,0,92,0.08)',
    shadowColor: COLORS.company,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  areaCardCandidateActive: {
    borderColor: COLORS.candidate,
    backgroundColor: 'rgba(0,163,255,0.08)',
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: COLORS.company },
  areaText: { color: COLORS.textSecondary, fontSize: 16, fontWeight: '600' },
  areaTextActive: { color: 'white', fontWeight: '800' },
  previewCard: {
    backgroundColor: 'rgba(255,255,255,0.02)',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginTop: 10,
  },
  pdfButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.02)',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },

  // AI Assessment Premium Styles
  professionSelectPrompt: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    padding: 16,
    marginTop: 15,
  },
  professionSelectPromptText: {
    color: COLORS.textSecondary,
    fontSize: 14,
    marginLeft: 10,
    flex: 1,
    lineHeight: 20,
  },
  aiPromoCard: {
    backgroundColor: 'rgba(0, 163, 255, 0.03)',
    borderWidth: 1.5,
    borderColor: 'rgba(0, 163, 255, 0.2)',
    borderRadius: 24,
    padding: 24,
    marginTop: 15,
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 4,
  },
  aiPromoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 16,
  },
  aiPromoBrainIconBg: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0, 163, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 163, 255, 0.25)',
  },
  aiPromoTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  aiPromoSubtitle: {
    color: COLORS.candidate,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
  },
  aiPromoDesc: {
    color: COLORS.textSecondary,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 20,
  },
  aiPromoBtn: {
    backgroundColor: COLORS.candidate,
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  aiPromoBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  aiPromoManualBtn: {
    alignItems: 'center',
    marginTop: 14,
    paddingVertical: 8,
  },
  aiPromoManualBtnText: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  backToAiBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginTop: 8,
  },
  backToAiBtnText: {
    color: COLORS.candidate,
    fontSize: 14,
    fontWeight: '700',
  },
  glowingCertCard: {
    backgroundColor: 'rgba(0, 163, 255, 0.04)',
    borderWidth: 1.5,
    borderColor: COLORS.candidate,
    borderRadius: 24,
    padding: 24,
    marginTop: 15,
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 6,
  },
  glowingCertHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  glowingCertTitle: {
    color: COLORS.candidate,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.5,
  },
  glowingCertLevel: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 16,
  },
  glowingCertFeedbackBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  glowingCertFeedbackLabel: {
    color: COLORS.textSecondary,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    marginBottom: 6,
  },
  glowingCertFeedbackText: {
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 22,
  },
  glowingCertActions: {
    flexDirection: 'row',
    gap: 12,
  },
  glowingCertBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 163, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0, 163, 255, 0.3)',
    height: 44,
    borderRadius: 22,
    gap: 6,
  },
  glowingCertBtnText: {
    color: COLORS.candidate,
    fontSize: 14,
    fontWeight: 'bold',
  },
  glowingCertBtnSec: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    height: 44,
    borderRadius: 22,
  },
  glowingCertBtnSecText: {
    color: '#64748b',
    fontSize: 14,
    fontWeight: '600',
  },
  aiModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  aiModalContent: {
    width: '90%',
    maxHeight: '85%',
    backgroundColor: '#0c0c0e',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  aiModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.03)',
  },
  aiModalHeaderTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  aiModalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiStepScroll: {
    padding: 24,
    paddingBottom: 40,
  },
  aiBrainIconBg: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(0, 163, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(0, 163, 255, 0.25)',
    marginBottom: 16,
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  aiStepTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 12,
  },
  aiStepSubtitle: {
    color: COLORS.textSecondary,
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: 20,
  },
  professionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 163, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(0, 163, 255, 0.15)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignSelf: 'center',
    marginBottom: 24,
  },
  professionPillText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  aiFeatureList: {
    gap: 14,
    marginBottom: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    padding: 18,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.03)',
  },
  aiFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  aiFeatureText: {
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
  },
  aiActionBtn: {
    width: '100%',
    backgroundColor: COLORS.candidate,
    paddingVertical: 16,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    marginTop: 10,
  },
  aiActionBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  aiProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  aiProgressText: {
    color: COLORS.candidate,
    fontSize: 13,
    fontWeight: '800',
  },
  aiProgressBarBg: {
    flex: 1,
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 3,
    marginLeft: 16,
  },
  aiProgressBarFill: {
    height: '100%',
    backgroundColor: COLORS.candidate,
    borderRadius: 3,
  },
  aiQuestionText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 26,
    marginBottom: 20,
  },
  aiInputContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1.5,
    borderColor: 'rgba(0, 163, 255, 0.15)',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  aiTextInput: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 22,
    textAlignVertical: 'top',
    minHeight: 120,
  },
  charCounter: {
    color: '#475569',
    fontSize: 12,
    alignSelf: 'flex-end',
    marginTop: 8,
    fontWeight: '600',
  },
  aiWarningHint: {
    color: '#475569',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 12,
  },
  scaleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginVertical: 24,
  },
  scaleItem: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scaleItemActive: {
    backgroundColor: 'rgba(0, 163, 255, 0.15)',
    borderColor: COLORS.candidate,
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  scaleNumber: {
    color: COLORS.textSecondary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  scaleNumberActive: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
  },
  scaleLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 32,
    paddingHorizontal: 4,
  },
  scaleLabelText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
  },
  aiAnalyzingContainer: {
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 350,
  },
  aiAnalyzingOrb: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.candidate,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
    marginBottom: 32,
  },
  aiAnalyzingTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 12,
  },
  aiAnalyzingText: {
    color: COLORS.textSecondary,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
  },
  certificateCard: {
    backgroundColor: '#111216',
    borderWidth: 1.5,
    borderColor: COLORS.candidate,
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    shadowColor: COLORS.candidate,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 8,
  },
  certificateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.04)',
    paddingBottom: 12,
  },
  certificateHeaderText: {
    color: COLORS.candidate,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 2,
  },
  certBody: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    marginBottom: 20,
  },
  certScoreContainer: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 163, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(0, 163, 255, 0.1)',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  certScore: {
    color: COLORS.candidate,
    fontSize: 32,
    fontWeight: '900',
  },
  certScoreSub: {
    color: COLORS.textSecondary,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginTop: 2,
  },
  certMeta: {
    flex: 1,
  },
  certTierLabel: {
    color: '#475569',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 4,
  },
  certTier: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  certProfession: {
    color: COLORS.candidate,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 4,
  },
  certDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    marginBottom: 20,
  },
  certFeedbackContainer: {
    gap: 6,
  },
  certFeedbackTitle: {
    color: COLORS.textSecondary,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  certFeedbackText: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 20,
  },
});
